FROM node:22-alpine

WORKDIR /app
# copy file page.json ไปไว้ใน /app
COPY package*.json ./

RUN npm install -g nodemon & npm install

# . แรก client .สอง /app
# ฝั่งซ้าย เครื่องเรา ขวา docker
COPY . .

# ปกติ react run port 5000 เราก็ส่งออกให้ คนอื่นเข้ามาที่  5000
EXPOSE 5000

CMD ["nodemon", "index.js"]